language: python
python:
- '3.5'
install: pip install -r requirements.txt
notifications:
  slack:
    on_success: change
    on_failure: change
script: pytest
deploy:
  provider:heroku
  app:jobmatcher
  api_key:
    secure: DV5xxpLynbnLH06baGDEY4BkQoxFGK/zZE9W8sPOGCnQpBPEP8S8aqdWgda3zYhHi5PJaK0LmA4lPbCDd4T0sear8fl9lqtf/ewShl6Sj8LyZkhW3zV0JOS4nSNXuHc7jq3mMk012YANu/DXVAHztj4O4JEPYm915sZGn2icMnr+W9A9p1GbnesgOnZLSdrBixzge5LT1g2bYV3Nv9uw5YQiXUYGK78IftLLSkbnT5O29K/0Isu88yMU+VptEHmZswcsI5bFgoEnJdgUeyOn/ljbVkwmQH08W+AOP7xrabsN1xP+5wHvsJitVIcGG5Mbe/Rl7zhvEYSFNo/ny5RWa43aob4xa2rOiQUKWKYcJ0WPYz2fKo1HkR+KxuUmr0AczNJsyoL2msTx1Q9f4XHJ2isRsQPZxNrhTOdlKDG//Quz7yIoqsZNhGBG8PRMS+LAuKKMFCJT4+SU3+z1JhSecggL50SR8MOiKP9DVKqdlM1JwCWdD4D6/uVC3pTE0cUa5s7qX0GOD8v39dyPfzgIeVyoG4VEDqaD0nuPBo/+n6HFvOaZuutXubcO56IEvZWP+dyunRxjIPWB4KxEaNSQ/mAJ4nPlgaxZoArwnxVT9mfambVn2jLIpNYpgl9PK3FvQotQ1LWF1Y09hSyMh7eI5RXuynokQ0+u0Y47bT8U6Xk=
