version: '3'

services:
  db:
    image: postgres
    networks:
      - db_net

  web:
    build: .
    links:
      - db
    networks:
      - db_net
    command: ./run_web.sh
#    command: python manage.py runserver 0.0.0.0:8010
    user: "501"
    volumes:
      - .:/matcher
    ports:
      - "8010:8010"
    depends_on:
      - db

networks:
  db_net:
