# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='potential',
            options={'permissions': (('can_view_potential', 'Can view potential employees applications'),)},
        ),
        migrations.AlterField(
            model_name='potential',
            name='nationality',
            field=models.CharField(default='Kenya', max_length=20),
        ),
    ]
